meta_product_name: "Watch List"
meta_title: "Watch List - For all movies lovers!"
meta_description: "Chez fan de cinéma on ne rechigne pas sur un vidéoprojecteur.
Encore plus quand on se déplace souvent et qu'on veut apprécier son film ou sa
série dans les meilleures conditions. On vous a sélectionné les meilleurs mini
vidéoprojecteurs. Découvrez tous nos tests, nos avis et nos comparatifs pour
avoir la meilleure qualité d'image possible. Grâce à nous, vous pourrez
chambrer vos collègues et leur dire qu'avec votre mini projecteur vous êtes
un vrai fan de cinéma !"
meta_image: "photo-meta.jpg" # should exist in `app/assets/images/`
